name: Fetch YouTube Videos
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch YouTube videos
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/cron/fetch-youtube" \
            -H "Authorization: Bearer ${{ secrets.CRON_API_KEY }}" \
            -H "Content-Type: application/json"
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
